# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='styles',
            new_name='style',
        ),
    ]
